pical_secretaria_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: SecretariaBundle:Default:index }
    
pical_secretaria_socios_index:
    pattern:  /socios/index
    defaults: { _controller: SecretariaBundle:Socios:index }


pical_secretaria_socio_edit:
    pattern:  /socio/edit/{idSocio}
    defaults: { _controller: SecretariaBundle:Socios:edit }
    requirements:
        idSocio: \d+
        
pical_secretaria_socio_form_edit:
    pattern:  /socio/form_edit/{idSocio}
    defaults: { _controller: SecretariaBundle:Socios:form_edit }
    requirements:
        idSocio: \d+
        
pical_secretaria_socio_view:
    pattern:  /socio/view/{idSocio}
    defaults: { _controller: SecretariaBundle:Socios:view }
    requirements:
        idSocio: \d+
        
pical_secretaria_socio_delete:
    pattern:  /socio/delete/{idSocio}
    defaults: { _controller: SecretariaBundle:Socios:delete }
    requirements:
        idSocio: \d+
        
pical_secretaria_socio_form_add:
    pattern:  /socio/form_add
    defaults: { _controller: SecretariaBundle:Socios:form_add }
    requirements:
        idSocio: \d+

pical_secretaria_socio_add:
    pattern:  /socio/add
    defaults: { _controller: SecretariaBundle:Socios:add }
    requirements:
        idSocio: \d+
        
pical_secretaria_escala_form_add:
    pattern:  /escala/form_add
    defaults: { _controller: SecretariaBundle:Escalas:form_add }
    requirements:
        idSocio: \d+
        
pical_secretaria_escala_add:
    pattern:  /escala/add
    defaults: { _controller: SecretariaBundle:Escalas:add }
    requirements:
        idSocio: \d+

pical_usuario_homepage:
    pattern:  /
    defaults: { _controller: SecretariaBundle:Seguridad:home }
    
pical_usuario_form_login:
    pattern:  /form_login
    defaults: { _controller: SecretariaBundle:Seguridad:form_login }
    
pical_usuario_login:
    pattern:  /login
    defaults: { _controller: SecretariaBundle:Seguridad:login }
    
pical_usuario_logout:
    pattern:  /logout
    defaults: { _controller: SecretariaBundle:Seguridad:logout }