<?php

namespace Proxies\__CG__\SecretariaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Socio extends \SecretariaBundle\Entity\Socio implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'SecretariaBundle\\Entity\\Socio' . "\0" . 'id', '' . "\0" . 'SecretariaBundle\\Entity\\Socio' . "\0" . 'nombre', '' . "\0" . 'SecretariaBundle\\Entity\\Socio' . "\0" . 'apellidos', '' . "\0" . 'SecretariaBundle\\Entity\\Socio' . "\0" . 'email', '' . "\0" . 'SecretariaBundle\\Entity\\Socio' . "\0" . 'direccion', '' . "\0" . 'SecretariaBundle\\Entity\\Socio' . "\0" . 'poblacion', '' . "\0" . 'SecretariaBundle\\Entity\\Socio' . "\0" . 'provincia', '' . "\0" . 'SecretariaBundle\\Entity\\Socio' . "\0" . 'cp', '' . "\0" . 'SecretariaBundle\\Entity\\Socio' . "\0" . 'numero_cuenta', '' . "\0" . 'SecretariaBundle\\Entity\\Socio' . "\0" . 'fecha_nacimiento', '' . "\0" . 'SecretariaBundle\\Entity\\Socio' . "\0" . 'url_foto', '' . "\0" . 'SecretariaBundle\\Entity\\Socio' . "\0" . 'escalas', '' . "\0" . 'SecretariaBundle\\Entity\\Socio' . "\0" . 'tipo_socio', '' . "\0" . 'SecretariaBundle\\Entity\\Socio' . "\0" . 'alta');
        }

        return array('__isInitialized__', '' . "\0" . 'SecretariaBundle\\Entity\\Socio' . "\0" . 'id', '' . "\0" . 'SecretariaBundle\\Entity\\Socio' . "\0" . 'nombre', '' . "\0" . 'SecretariaBundle\\Entity\\Socio' . "\0" . 'apellidos', '' . "\0" . 'SecretariaBundle\\Entity\\Socio' . "\0" . 'email', '' . "\0" . 'SecretariaBundle\\Entity\\Socio' . "\0" . 'direccion', '' . "\0" . 'SecretariaBundle\\Entity\\Socio' . "\0" . 'poblacion', '' . "\0" . 'SecretariaBundle\\Entity\\Socio' . "\0" . 'provincia', '' . "\0" . 'SecretariaBundle\\Entity\\Socio' . "\0" . 'cp', '' . "\0" . 'SecretariaBundle\\Entity\\Socio' . "\0" . 'numero_cuenta', '' . "\0" . 'SecretariaBundle\\Entity\\Socio' . "\0" . 'fecha_nacimiento', '' . "\0" . 'SecretariaBundle\\Entity\\Socio' . "\0" . 'url_foto', '' . "\0" . 'SecretariaBundle\\Entity\\Socio' . "\0" . 'escalas', '' . "\0" . 'SecretariaBundle\\Entity\\Socio' . "\0" . 'tipo_socio', '' . "\0" . 'SecretariaBundle\\Entity\\Socio' . "\0" . 'alta');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Socio $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', array($nombre));

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', array());

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setApellidos($apellidos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApellidos', array($apellidos));

        return parent::setApellidos($apellidos);
    }

    /**
     * {@inheritDoc}
     */
    public function getApellidos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApellidos', array());

        return parent::getApellidos();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setDireccion($direccion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDireccion', array($direccion));

        return parent::setDireccion($direccion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDireccion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDireccion', array());

        return parent::getDireccion();
    }

    /**
     * {@inheritDoc}
     */
    public function setPoblacion($poblacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPoblacion', array($poblacion));

        return parent::setPoblacion($poblacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getPoblacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPoblacion', array());

        return parent::getPoblacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setProvincia($provincia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProvincia', array($provincia));

        return parent::setProvincia($provincia);
    }

    /**
     * {@inheritDoc}
     */
    public function getProvincia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProvincia', array());

        return parent::getProvincia();
    }

    /**
     * {@inheritDoc}
     */
    public function setCP($cp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCP', array($cp));

        return parent::setCP($cp);
    }

    /**
     * {@inheritDoc}
     */
    public function getCP()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCP', array());

        return parent::getCP();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroCuenta($numeroCuenta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroCuenta', array($numeroCuenta));

        return parent::setNumeroCuenta($numeroCuenta);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroCuenta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroCuenta', array());

        return parent::getNumeroCuenta();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaNacimiento($fechaNacimiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaNacimiento', array($fechaNacimiento));

        return parent::setFechaNacimiento($fechaNacimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaNacimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaNacimiento', array());

        return parent::getFechaNacimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setEscalas($escalas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEscalas', array($escalas));

        return parent::setEscalas($escalas);
    }

    /**
     * {@inheritDoc}
     */
    public function getEscalas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEscalas', array());

        return parent::getEscalas();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoSocio($tipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoSocio', array($tipo));

        return parent::setTipoSocio($tipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoSocio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoSocio', array());

        return parent::getTipoSocio();
    }

    /**
     * {@inheritDoc}
     */
    public function setAlta($alta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlta', array($alta));

        return parent::setAlta($alta);
    }

    /**
     * {@inheritDoc}
     */
    public function getAlta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlta', array());

        return parent::getAlta();
    }

    /**
     * {@inheritDoc}
     */
    public function esInfantil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'esInfantil', array());

        return parent::esInfantil();
    }

}
